# Config file for automatic testing at travis-ci.org

language: python
python:
    - 3.6

# Command to install miniconda so we can get dolpyn (fenics and mshr)
install:
    - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p "$HOME"/miniconda
    - source "$HOME"/miniconda/etc/profile.d/conda.sh
    - conda config --set always_yes yes --set changeps1 no --set auto_update_conda false
    - conda config --add channels conda-forge
    - conda install -c conda-forge --file requirements_conda.txt
# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - pip install -U tox-travis
    - pip install -r requirements.txt

# Command to run tests, e.g. python setup.py test
script: tox

# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
deploy:
    provider: pypi
    distributions: sdist bdist_wheel
    user: johnjarmitage
    password:
        secure: PLEASE_REPLACE_ME
    on:
        tags: true
        repo: johnjarmitage/flem
        python: 3.6
