# Config file for automatic testing at travis-ci.org

before_install:
    - sudo apt-get update
    - sudo apt-get install libgdal-dev

language: python
python:
    - 3.6

# Command to install miniconda so we can get dolpyn (fenics and mshr)
# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p "$HOME"/miniconda
    - source "$HOME"/miniconda/etc/profile.d/conda.sh
    - conda config --set always_yes yes --set changeps1 no --set auto_update_conda false
    - conda update -q conda
    # Useful for debugging any issues with conda
    - conda info -a
    # Create flem environment
    - conda env create -f environment.yml
    - conda activate flem
#    - conda config --add channels conda-forge
#    - conda install -c conda-forge --file requirements_conda.txt
    - conda install -c conda-forge --file requirements_dev.txt
    # downgrade poppler because of this: https://github.com/ContinuumIO/anaconda-issues/issues/9449
    # - conda install "poppler<0.62"

# Command to run tests, e.g. python setup.py test
script:
    #- conda activate flem
    #- pip install -r requirements.txt
    - export PYTHONPATH=.
    - py.test

# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
deploy:
    provider: pypi
    distributions: sdist bdist_wheel
    user: johnjarmitage
    password:
        secure:
    on:
        tags: true
        repo: johnjarmitage/flem
        python: 3.6
